// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaProgra2.Models;

#nullable disable

namespace PruebaProgra2.Migrations
{
    [DbContext(typeof(ProyectoPrograDbContext))]
    partial class ProyectoPrograDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaProgra2.Models.EstadosTarea", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EstadoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoId")
                        .HasName("PK__EstadosT__FEF86B605F61D9F6");

                    b.HasIndex(new[] { "NombreEstado" }, "UQ__EstadosT__6CE50615FBEA5A6A")
                        .IsUnique();

                    b.ToTable("EstadosTarea", (string)null);
                });

            modelBuilder.Entity("PruebaProgra2.Models.LogsEjecucion", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoID");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TareaId")
                        .HasColumnType("int")
                        .HasColumnName("TareaID");

                    b.HasKey("LogId")
                        .HasName("PK__LogsEjec__5E5499A88F583209");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TareaId");

                    b.ToTable("LogsEjecucion", (string)null);
                });

            modelBuilder.Entity("PruebaProgra2.Models.PrioridadesTarea", b =>
                {
                    b.Property<int>("PrioridadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrioridadID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrioridadId"));

                    b.Property<string>("NivelPrioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PrioridadId")
                        .HasName("PK__Priorida__393917CE6F4E24DE");

                    b.HasIndex(new[] { "NivelPrioridad" }, "UQ__Priorida__9A68DDA1AEAA00E4")
                        .IsUnique();

                    b.ToTable("PrioridadesTarea", (string)null);
                });

            modelBuilder.Entity("PruebaProgra2.Models.Tarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TareaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoID");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PrioridadId")
                        .HasColumnType("int")
                        .HasColumnName("PrioridadID");

                    b.HasKey("TareaId")
                        .HasName("PK__Tareas__5CD836717B6C9285");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PrioridadId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("PruebaProgra2.Models.LogsEjecucion", b =>
                {
                    b.HasOne("PruebaProgra2.Models.EstadosTarea", "Estado")
                        .WithMany("LogsEjecucions")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK_LogsEjecucion_EstadosTarea");

                    b.HasOne("PruebaProgra2.Models.Tarea", "Tarea")
                        .WithMany("LogsEjecucions")
                        .HasForeignKey("TareaId")
                        .IsRequired()
                        .HasConstraintName("FK_LogsEjecucion_Tareas");

                    b.Navigation("Estado");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("PruebaProgra2.Models.Tarea", b =>
                {
                    b.HasOne("PruebaProgra2.Models.EstadosTarea", "Estado")
                        .WithMany("Tareas")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Tareas_EstadosTarea");

                    b.HasOne("PruebaProgra2.Models.PrioridadesTarea", "Prioridad")
                        .WithMany("Tareas")
                        .HasForeignKey("PrioridadId")
                        .IsRequired()
                        .HasConstraintName("FK_Tareas_PrioridadesTarea");

                    b.Navigation("Estado");

                    b.Navigation("Prioridad");
                });

            modelBuilder.Entity("PruebaProgra2.Models.EstadosTarea", b =>
                {
                    b.Navigation("LogsEjecucions");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("PruebaProgra2.Models.PrioridadesTarea", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("PruebaProgra2.Models.Tarea", b =>
                {
                    b.Navigation("LogsEjecucions");
                });
#pragma warning restore 612, 618
        }
    }
}
